/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 space_boi.glb -T 
Files: space_boi.glb [3.14MB] > D:\Projects\3d-portfolio\public\models\space_boi-transformed.glb [104.5KB] (97%)
Author: silvercrow101 (https://sketchfab.com/silvercrow101)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-boi-f6a8c6a6727b4f2cb020c8b50bb2ee60
Title: space boi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceBoi(props) {
  const { nodes, materials } = useGLTF('/models/space_boi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/space_boi-transformed.glb')
